ZOTERO_LIBRARY_ID = "5650543"
ZOTERO_LIBRARY_TYPE = "group"

BABEL_DEFAULT_LOCALE = "en_US"
BABEL_DEFAULT_TIMEZONE = "Australia/Sydney"

SHOW_PROCESSING_TIME = true

# Most parameters have a default value. Deleting such parameter from this file
# will not disable it but merely reset it to its default value.

[kerko.features]

download_attachment_new_window = false
download_item = true
download_results = true
download_results_max_count = 100
open_in_zotero_app = false
open_in_zotero_web = false
print_item = true
print_results = true
print_results_max_count = 0
relations_links = false
relations_initial_limit = 5
relations_sort = "author_asc"
results_abstracts = true
results_abstracts_max_length = 0
results_abstracts_max_length_leeway = 0
results_abstracts_toggler = true
results_attachment_links = false
results_url_links = true

[kerko.feeds]

formats = []
fields = ["id", "data"]
max_days = 0

[kerko.meta]

title = "PhDs.io"
google_analytics_id = "G-TFJCZ2EWMZ"

[kerko.pagination]

page_len = 7
pager_links = 5

[kerko.breadcrumb]

enabled = true
include_current = true
text_max_length = 50
text_max_length_leeway = 10

[kerko.link_groups]

[[kerko.link_groups.navbar]]
text = "Home"
type = "endpoint"
endpoint = "kerko.search"

[[kerko.link_groups.navbar]]
text = "About"
type = "url"
url = "/about"

[[kerko.link_groups.breadcrumb_base]]
text = "PhDs.io"
type = "url"
url = "/"

[kerko.performance]
whoosh_index_memory_limit = 256
whoosh_index_processors = 2

[kerko.zotero]

# csl_style = "apa"
csl_style = "apa-no-doi-no-issue"
locale = "en-US"
item_include_re = ''
item_exclude_re = ''
child_include_re = ''
child_exclude_re = '^_'
attachment_mime_types = ["application/pdf"]
tag_include_re = '\[Topic\] (?P<kerko>.*)'
tag_exclude_re = '^_'

[kerko.search]

fulltext = true
whoosh_language = "en"


[kerko.facets]

[kerko.facets.journals]
enabled = true
type = "collection"
collection_key = "ZT72UUC6"
filter_key = "journal"
title = "Journals"
weight = 50
initial_limit = 10
initial_limit_leeway = 2

[kerko.facets.rankings]
enabled = true
type = "collection"
collection_key = "Z76F9NJW"
filter_key = "ranking"
title = "Ranking"
weight = 65
initial_limit = 10
initial_limit_leeway = 2

[kerko.facets.oa]
enabled = true
type = "collection"
collection_key = "JKQ8PAV4"
filter_key = "oa"
title = "Open Access"
weight = 75
initial_limit = 10
initial_limit_leeway = 2

[kerko.facets.tag]
enabled = true
weight = 100
initial_limit = 10
initial_limit_leeway = 2
sort_by = ["count"]

[kerko.facets.item_type]
enabled = false
weight = 200
initial_limit = 0
initial_limit_leeway = 2
sort_by = ["label"]

[kerko.facets.year]
enabled = true
weight = 70
initial_limit = 5
initial_limit_leeway = 2
sort_by = ["label"]

[kerko.templates]
base = "kerkoapp/base.html.jinja2"
layout = "kerkoapp/layout.html.jinja2"
item = "kerkoapp/item.html.jinja2"
search = "kerkoapp/search.html.jinja2"

# My own config
# These must be defined.
[custom]
show_macquarie_logo = false
# DO NOT DISPLAY PDF!!!
show_document = false
# Show Open Access, however.
show_open_access = true
open_access_tag = "[Open Access]"
# Ranking tags
ft50_tag = "[Ranking] FT50"
utd24_tag = "[Ranking] UTD24"
abdc_tag = "[Ranking] ABDC-A*" # Only tag A*
# Flash message / Announcement
show_flash_message = true
flash_message_path = "flash_message.txt"

[open_graph]
og_title = "PhDs.io - Knowledge that Transforms"
og_description = "Navigate high-quality research papers in finance, economics, accounting, and related fields. PhDs.io offers a simplified literature discovery experience."
